import { Newsreader, Outfit, Ovo, Quintessential } from "next/font/google";
import "./globals.css";
import Topscroll from './components/Topscroll';

const outfit = Outfit({
  subsets: ["latin"], weight:["400", "500", "600", "700"]
});

const ovo = Ovo({
  subsets: ["latin"], weight:["400"]
});
const quintessential = Quintessential({
  subsets: ["latin"], weight:["400"]
});

const newsreader = Newsreader({
  subsets: ["latin"], weight:["400", "500", "600", "700"]
});

export const metadata = {
  title: "Next App Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body
        className={`${newsreader.variable} ${outfit.variable} ${ovo.variable} antialiased`}
      >
        <Topscroll />
        {children}
      </body>
    </html>
  );
}
